ARG IMAGE=nginx:1.21-alpine
FROM $IMAGE AS build

# Set permissions for 'nginx' user
COPY ./src/bf2sclone /src/bf2sclone
WORKDIR /src/bf2sclone
RUN chown -R nginx:nginx . \
    && find . -type d -exec chmod 750 {} \; \
    && find . -type f -exec chmod 640 {} \;

FROM $IMAGE AS dev

# Add default configs
COPY config/bf2sclone/nginx/nginx.conf /etc/nginx/nginx.conf

FROM dev AS prod

COPY --from=build /src /src
