name: ci-master-pr

on:
  push:
    branches:
    - master
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        testenv:
          - dev
          - prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # This is commented out, so we use the default 'docker' driver instead of the 'docker-container' driver. When using 'docker-container' driver, there appears to be a rate limit on writes on Github CI which causes buildx to fail with error code 17 when it is exporting to cache
    # - name: Set up Docker Buildx
    #   id: buildx
    #   uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers (asp)
      uses: actions/cache/restore@v3  # Restore cache but don't save it at end of job
      with:
        path: /tmp/.buildx-cache-asp
        key: ${{ runner.os }}-buildx-asp-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-asp-
          ${{ runner.os }}-buildx-

    - name: Cache Docker layers (bf2sclone)
      uses: actions/cache/restore@v3  # Restore cache but don't save it at end of job
      with:
        path: /tmp/.buildx-cache-bf2sclone
        key: ${{ runner.os }}-buildx-bf2sclone-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-bf2sclone-
          ${{ runner.os }}-buildx-

    - name: Print buildx and compose
      run: |
        set -eu
        docker buildx ls
        docker compose version

    - name: Integration test (dev)
      if: matrix.testenv == 'dev'
      run: |
        set -eux
        ./test/test.sh dev 1 1

    - name: Integration test 1 (prod)
      if: matrix.testenv == 'prod'
      run: |
        set -eux
        ./test/test.sh prod1 1 1

    - name: Integration test 2 (prod)
      if: matrix.testenv == 'prod'
      run: |
        set -eux

        # Don't publish coredns ports to prevent conflict with system-resolved on github CI
        # sed -i '$!N;s@ports:\n      - 53:53.*@@;P;D' docker-compose.yml

        # Make coredns listen on localhost only to prevent conflict with system-resolved on github CI
        sed -i 's/- 53:53/- 127.0.0.1:53:53/' docs/full-bf2-stack-example/docker-compose.yml

        ./test/test.sh prod2 1 1

  build:
    strategy:
      matrix:
        variant:
          - asp
          - bf2sclone
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        lscpu
        free
        df -h
        pwd
        docker info
        docker version

    # See: https://github.com/docker/build-push-action/blob/v2.6.1/docs/advanced/cache.md#github-cache
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache-${{ matrix.variant }}
        key: ${{ runner.os }}-buildx-${{ matrix.variant }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.variant }}-
          ${{ runner.os }}-buildx-

    # This step generates the docker tags
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ github.repository }}
        # type=ref,event=pr generates tag(s) on PRs only. E.g. 'pr-123-<variant>', 'pr-123-abc0123-<variant>'
        # type=ref,event=branch generates tag(s) on branch only. E.g. 'master-<variant>', 'master-abc0123-<variant>'
        # type=ref,event=tag generates tag(s) on tags only. E.g. 'v0.0.0-<variant>', 'v0.0.0-abc0123-<variant>'
        tags: |
          type=ref,suffix=-${{ matrix.variant }},event=pr
          type=ref,suffix=-{{sha}}-${{ matrix.variant }},event=pr
          type=ref,suffix=-${{ matrix.variant }},event=branch
          type=ref,suffix=-{{sha}}-${{ matrix.variant }},event=branch
          type=ref,suffix=-${{ matrix.variant }},event=tag
          type=ref,suffix=-{{sha}}-${{ matrix.variant }},event=tag
        # Disable 'latest' tag
        flavor: |
          latest=false

    - name: Login to Docker Hub registry
      # Run on master and tags
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_REGISTRY_USER }}
        password: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}

    - name: Build (PRs)
      # Run on pull requests
      if: github.event_name == 'pull_request'
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile.${{ matrix.variant }}
        context: '.'
        target: prod
        platforms: linux/amd64
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.variant }}
        cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.variant }}-new,mode=max

    - name: Build and push
      # Run on master and tags
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile.${{ matrix.variant }}
        context: '.'
        target: prod
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/s390x
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.variant }}
        cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.variant }}-new,mode=max

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache-${{ matrix.variant }}
        mv /tmp/.buildx-cache-${{ matrix.variant }}-new /tmp/.buildx-cache-${{ matrix.variant }}

  update-draft-release:
    needs: [test, build]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-draft-release:
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true
          name: ${{ github.ref_name }} # E.g. 'master' or 'v1.2.3'
          tag: ${{ github.ref_name }} # E.g. 'master' or 'v1.2.3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-dockerhub-description:
    needs: [test, build]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_REGISTRY_USER }}
        password: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}
        repository: ${{ github.repository }}
        short-description: ${{ github.event.repository.description }}
